name: EnjeezSystem CI/CD

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
    - name: Notify Deployment
      run: |
        echo "✅ Build and test completed successfully!"
        echo "🚀 Deploying version ${{ github.sha }} to Staging..."
        echo "🔜 Actual deployment steps will be added later"
